# Generated by Django 5.0.6 on 2024-08-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "data_send",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="укажите количество просмотров товара",
                null=True,
                verbose_name="Количество просмотров",
            ),
        ),
    ]
